config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place

  RATINGS = {
    '1 star': '1_star',
    '2 stars': '2_stars',
    '3 stars': '3_stars',
    '4 stars': '4_stars',
    '5 stars': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments

  geocoded_by :address
  after_validation :geocode

  validates :name, :address, :description, presence: true
  validates :name, length: { minimum: 3, too_short: "Please make sure your name is at least %{count} characters" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

    def comment_params
      params.require(:comment).permit(:message,:rating)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @place = Place.find(params[:id])

    if current_user != @place.user
      return render text: 'You must have created the place to edit it!', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if current_user != @place.user
      return render text: 'You must have created the place to delete it!', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicRoomFinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'MusicRoomFinder', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle nav-item nav-link"></i>Add a place
            <% end %>
          </li>
        </ul>
        <ul class = "navbar-nav">
          <% if user_signed_in? %>
            <li class = "nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class = "nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class = "nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          </ul>
          <% end %>
      </div>
    </nav>

    <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<br />
<div class = "contained-fluid col-10 offset-1 booyah-box">
<h1>Edit <%= link_to @place.name, place_path %></h1>
<br />
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Edit', class: "btn btn-primary col-12 col-md-5" %>
  <% end %>

</div>

app/views/places/index.html.erb
<br />
<% @places.each do |place| %>
  <div class = "booyah-box col-10 offset-1 place-box">
    <h1><%= link_to place.name, place_path(place) %></h1>
    <i><%= place.address %></i><br />
    <p><%= place.description %> </p>

    <% if place.user.present? %>
    <small><%= place.user.email %></small>
    <% end %>
  </div>
  <br />
<% end %>
<%= will_paginate @places, :class => 'apple_pagination' %>

app/views/places/new.html.erb
<br />
<div class = "booyah-box col-10 offset-1">
  <h2>Enter your place details</h2>
  <br />
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: "btn btn-primary col-12 col-md-5" %>
  <% end %>
</div>

app/views/places/show.html.erb
<br />
<div class = "container-fluid col-10 offset-1 booyah-box">
<h1 id="show-page-header"><%= @place.name %></h1>
  <div class="float-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to edit_place_path(@place), class: 'btn btn-secondary' do %>
        <i class="fa fa-pencil" aria-hidden="true"></i> Edit
      <% end %>
      <%= link_to place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' do %>
        <i class="fa fa-trash" aria-hidden="true"></i> Delete
      <% end %>
    <% end %>
  </div>
  <br /><i><%= @place.address %></i>
  <br /><br />
  <% if @place.latitude.present? && @place.longitude.present? %>
    <script>
      function initMap() {
        var location = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: location
        });
        var marker = new google.maps.Marker({
          position: location,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCOz4QIsVKc1PoR0LojGMbj-9Jsgf0VUzA&callback=initMap">
    </script>
    <div id="map"></div>
  <% end %> 
  <br />
  <p><%= @place.description %> </p>
</div>

<br />

<div class = "container-fluid col-10 offset-1 booyah-box">
<h3>Comments</h3>
<br />
<% @place.comments.each do |comment| %>
  <div class>
    <blockquote class = "blockquote col-8 offset-1">
    <% if comment.humanized_rating.present? %>
    <% end %>
      <b><%= comment.humanized_rating %></b> -
        <%= comment.message %>
      <footer class="blockquote-footer"><%= comment.user.email %></footer>
    </blockquote>
  </div>
<% end %>
</div>

<br />

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary col-10 offset-1" data-toggle="modal" data-target="#myModal">
  Add a comment
</button>

<br />
<br />

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">
        <h2>Add a comment</h2>
        <br />
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
          <%= f.input :message %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add a comment", class: 'btn btn-primary' %>
       <% end %>
      </div>
    </div>
  </div>
</div>